loadshed/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('timetable/', include('timetable.urls', namespace='timetable')),
    path('admin/', admin.site.urls),
] 

timetable/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'timetable'

urlpatterns = [
    
    path('',views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search',views.search, name='search'),
]

timetable/models.py
from django.db import models
from model_utils import Choices

# Create your models here.

class Area(models.Model):
    area = models.CharField(max_length=50, null=True)
    

    def __str__(self):
        return self.area.upper()

class AreaCode(models.Model):
    code = models.CharField(max_length=4, null=True)
    # area = models.ForeignKey('Area', on_delete=models.CASCADE)

    def __str__(self):
        return self.code

class Schedule(models.Model):
    DAYS = Choices('Monday','Tuesday', 'Wednesday', 'Thursday', 'Friday')
    STAGE = Choices('ONE', 'TWO')
    PEAK  = Choices('AM', 'PM')
    area = models.ForeignKey('Area', on_delete=models.CASCADE)
    code = models.ForeignKey('AreaCode', on_delete=models.CASCADE) 
    day = models.CharField(choices=DAYS, default = DAYS.Monday, max_length = 20)
    stage = models.CharField(choices=STAGE, default = STAGE.ONE, max_length=20)
    peak = models.CharField(choices=PEAK, default = PEAK.AM, max_length=2)

    def __str__(self):
        return self.area

timetable/views.py
from django.shortcuts import render
from .models import Schedule


# Create your views here.




def home(request):

    # times = Schedule.objects.all()
    # print(times)

    return render(request, 'home.html')

def search(request):

    location = request.GET['location']
    location = str(location.upper())

    times = Schedule.objects.filter(area__area=location)
    if not times:
        found = False
        return render(request, 'result.html', {'found':found})
    else:
        print(location)
        return render(request, 'result.html', {'times' : times, 'location':location})

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href=" {% static 'style.css' %}" rel="stylesheet" type="text/css" />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" />
    <title>Load Shedding Schedule</title>
  </head>
  <body>
    <article>
      <header>
        <nav class="nav-bar">
          <img src="{% static 'zetdc-logo.png' %} " class="logo" />
          <a href="#">ZESA Load Shedding Schedule</a>
        </nav>
      </header>
      <main>
        <div id="main-heading">
          Find out what time you have power
        </div>
        <div id="search-section">
          <form action="{%url 'timetable:search'%}">
            <input
              type="text"
              placeholder="Enter Location"
              class="search-input"
              name="location"
            />
            <button id="search-btn" type='submit'><i class="fas fa-search"></i> Search</button>
          </form>
        </div>

        <div id = "search-results">
                <div id="card">
                    <div id="card-header">
                        <h1 class="location">Area Name</h1>
                       
                    </div>
                    <div id="card-body">
                        <h3>Power Schedule</h3>
                        <table style="width:90%">
                            <tr>
                                <th>Day</th>
                                <th>Peak</th>
                            </tr>
                            <tr>
                                <td>Mon-Fri</td>
                                <td>AM/PM</td>
                            </tr>
        
                        </table>
                    </div>
                    <div id="card-footer">
                        <h6>Key</h6>
                        <h6>AM: No Electricity Between 6:00am and 1:00pm</h6>
                        <h6>PM: No Electricity Between 1:00pm and 8:00pm</h6>
                    </div>
                </div>
            </div>
        </main>
    </main>
    <footer class="footer-section">
      &copy 2019 Gisul Solutions - ZETDC Training
    </footer>
  </article>
</body>
</html>

templates/result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href=" {% static 'style.css' %}" rel="stylesheet" type="text/css" />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" />
    <title>Load Shedding Schedule</title>
  </head>
  <body>
    <article>
      <header>
        <nav class="nav-bar">
          <img src="{% static 'zetdc-logo.png' %} " class="logo" />
          <a href="#">ZESA Load Shedding Schedule</a>
        </nav>
      </header>
      <main>
        <div id="main-heading">
          Find out what time you have power
        </div>
        <div id="search-section">
          <form action="{%url 'timetable:search'%}" >
            <input
              type="text"
              placeholder="Enter Location"
              class="search-input"
              name="location"
            />
            <button id="search-btn" type='submit'><i class="fas fa-search"></i> Search</button>
          </form>
        </div>
        {% if times is none %} 
        <div id = "search-results">
                <div id="card">
                    <div id="card-header">
                        <h1 class="location">Please Search Your Location Above</h1>
                       
                    </div>
                    <div id="card-body">
                        <h3>Power Schedule As Advised by ZESA</h3>
                        <table style="width:90%">
                            <tr>
                                <th>Day</th>
                                <th>Peak</th>
                            </tr>
                            <tr>
                                <td>Mon-Fri</td>
                                <td>?</td>
                            </tr>
        
                        </table>
                    </div>
                    <div id="card-footer">
                        <h6>Key</h6>
                        <h6>AM: No Electricity Between 6:00am and 1:00pm</h6>
                        <h6>PM: No Electricity Between 1:00pm and 8:00pm</h6>
                    </div>
                </div>
            </div>
        {% else %}
        <div id = "search-results">
                <div id="card">
                    <div id="card-header">
                        <h1 class="location">{{location}}</h1>
                        <h6 class="area-code">Area Code: </h6>
                    </div>
                    <div id="card-body">
                        <h3>Power Schedule</h3>
                        <table style="width:90%">
                            <tr>
                                <th>Day</th>
                                <th>Peak</th>
                            </tr>
                            
                            {% for item in times%}
                            <tr>
                                
                                <th>
                                    {{ item.day}}
                                </th>   
                                <th>
                                {{ item.peak }}
                                </th>
                            
                            </tr>
                            {%endfor%}
                        </table>
                    </div>
                    <div id="card-footer">
                        <h6>Key</h6>
                        <h6>AM: No Electricity Between 6:00am and 1:00pm</h6>
                        <h6>PM: No Electricity Between 1:00pm and 8:00pm</h6>
                    </div>
                </div>
            </div>
        {% endif %}
        </main>
      </main>
      <footer class="footer-section">
        &copy 2019 Gisul Solutions - ZETDC Training
      </footer>
    </article>
  </body>
</html>